/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

/* $Id: nace.h,v 1.1.1.1 2002/07/19 20:23:19 sienkiew Exp $ */

#include <rpc/types.h>


struct net_data {
	char *cmd;
	struct {
		u_int reply_len;
		char *reply_val;
	} reply;
	int clientId;
};
typedef struct net_data net_data;
bool_t xdr_net_data();

struct ace_server_res {
	int errno;
	union {
		net_data res_data;
	} ace_server_res_u;
};
typedef struct ace_server_res ace_server_res;
bool_t xdr_ace_server_res();

#define NET_ACE ((u_long)0x20000101)
#define NET_ACE_VERS ((u_long)1)
#define ACE_SERVER ((u_long)1)
extern ace_server_res *ace_server_1();
