#!/bin/csh -f
#
# script to make distribution tar files - edit as needed each time.
#
# $Id: MAKE_OTHERS,v 1.1.1.1 2002/07/19 20:23:37 sienkiew Exp $

if ($#argv != 2) then
#  echo 'you need 2 parameters:  MAKE_OTHERS 4_3a alpha ALPHA_4_OPT
  echo 'you need 2 parameters:  MAKE_OTHERS alpha ALPHA_4_OPT'
  exit 1
  endif

setenv ici `pwd`
cd ~/distrib   # test exitence 

cd $ici 

set version = `$ici/wtools/aceGetVersion.pl $ici/wnq`

echo 'I will prepare the distribution in ~/distrib'
echo "version $version for $1 using bin.$2"

\rm -r bin
mv bin.$2 bin
cp wtools/xcl bin
tar cf ~/distrib/bin.$1.$version.tar \
	wspec wdoc wquery wscripts wgf wtools \
	bin/xace bin/xaceclient \
	bin/tace bin/acediff bin/aceclient bin/gnbkclient
mv bin bin.$2

cd ~/distrib
compress ~/distrib/bin.$1.$version.tar

